### ISSUE TITLE
Perfdata feature not working in V3

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#144] opened 2023-03-02 06:18 UTC
**Describe the bug**
In V2 it was possible to extract performance data from icinga checks and display them on cards instead of the status.

**Expected behavior**
Same as V2:
![image](https://user-images.githubusercontent.com/21114973/222347293-577d99fb-9bfd-4b42-87d0-d861690fcdd8.png)

- in dashboard edit mode after selecting an icinga check it's possible to select from a dropdown of its perfdata which to display
- in dashboard edit mode it is possible to chose a default value for when the perfdata is not available
- in dashboard view mode the current value for the perfdata is displayed

**Screenshots**
V2 usage in tbs/abc-australia-south-pacific-clone
![image](https://user-images.githubusercontent.com/21114973/222346711-354c5765-7851-4dbc-aa61-b9924b1c36bb.png)
V3 current behaviour:
![image](https://user-images.githubusercontent.com/21114973/222346872-8cf1387c-5f29-438f-ab05-f8485da042cf.png)

**Comment by ollytom** [comment] 2023-03-02 06:25
Duplicate of #132

**Closed by ollytom** 2023-03-02 06:25 UTC
