### ISSUE TITLE
Checkline elements cannot be linked to icinga checks

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#140] opened 2023-02-20 06:31 UTC
**Describe the bug**
no spaces to edit anything about the check

![image](https://user-images.githubusercontent.com/21114973/220029388-07ea3ec9-c5b8-4c06-a800-3433a65518d4.png)

suspect this is the same underlying cause as #139 - line.jsx has not been updated to the new object

**Comment by ollytom** [comment] 2023-02-28 05:29
Duplicate of https://github.com/meerkat-dashboard/meerkat/issues/139

**Closed by ollytom** 2023-02-28 05:29 UTC
Labels: ui
