### ISSUE TITLE
Plugin Output feature not working

### ISSUE THREAD

**Issue by s2156945** [meerkat-dashboard/meerkat#145] opened 2023-03-02 06:27 UTC
**Describe the bug**
In V2 it was possible to extract text from icinga check output using a regex and display them on cards instead of the status.

**Expected behavior**
Same as V2:
- in dashboard edit mode after selecting an icinga check it's possible to select from a dropdown "Plugin Output" as an alternative to (#144) perfdata and extract it with a regex
- if the regex data was not found then the some default text could be specified to be displayed

**Example V2**
![image](https://user-images.githubusercontent.com/21114973/222348416-431d8f46-c37a-443a-893c-654e0abe61cf.png)

**Current behaviour V3**
![image](https://user-images.githubusercontent.com/21114973/222348485-c6435143-0f3f-4a85-a269-f0579908acae.png)

**Comment by ollytom** [comment] 2023-03-02 07:14
Duplicate of #131

**Closed by ollytom** 2023-03-02 07:14 UTC
