### ISSUE TITLE
Write version into github actions for display on front page

### ISSUE THREAD

**Issue by davekempe** [meerkat-dashboard/meerkat#125] opened 2022-10-10 01:55 UTC
We used to have a feature where the version was going to be written to the HTML on the front page, but it required manual adjustment. The git revision would make more sense, so we can be sure we are lodging bugs against the correct thing.

Modifying the github action that spits out the git revision id into a text file that gets included in the tarball, or in the HTML of the site should be easy enough.

**Comment by ollytom** [comment] 2022-10-12 23:39
Duplicate of #60

**Closed by ollytom** 2022-10-12 23:39 UTC
